import WpeText from "./options/components/WpeText";
import WpeTextarea from "./options/components/WpeTextarea";
import WpeUrl from "./options/components/WpeUrl";
import WpeNumber from "./options/components/WpeNumber";
import WpeSelect from "./options/components/WpeSelect";
import WpeColor from "./options/components/WpeColor";
import WpeSlider from "./options/components/WpeSlider";
import WpeToggle from "./options/components/WpeToggle";
import WpeDateTime from "./options/components/WpeDateTime";
import WpeTime from "./options/components/WpeTime";
import WpeTransfer from "./options/components/WpeTransfer";
import WpeButtonGroup from "./options/components/WpeButtonGroup";
import WpeButtonSet from "./options/components/WpeButtonSet";
import WpeRadio from "./options/components/WpeRadio";
import WpeLinkColor from "./options/components/WpeLinkColor";
import WpeInfo from "./options/components/WpeInfo";
import WpeDivider from "./options/components/WpeDivider";
import WpeImageSelect from "./options/components/WpeImageSelect";
import WpeEditor from "./options/components/WpeEditor";
import WpeMedia from "./options/components/WpeMedia";
import WpeBackground from "./options/components/WpeBackground";
import WpeSection from "./options/components/WpeSection";
import WpeHeading from "./options/WpeHeading";
import WpeHelp from "./options/WpeHelp";
import WpeOptionsPage from "./options/WpeOptionsPage";

Vue.component("wpe-text", WpeText);
Vue.component("wpe-textarea", WpeTextarea);
Vue.component("wpe-url", WpeUrl);
Vue.component("wpe-number", WpeNumber);
Vue.component("wpe-select", WpeSelect);
Vue.component("wpe-color", WpeColor);
Vue.component("wpe-slider", WpeSlider);
Vue.component("wpe-toggle", WpeToggle);
Vue.component("wpe-date-time", WpeDateTime);
Vue.component("wpe-time", WpeTime);
Vue.component("wpe-transfer", WpeTransfer);
Vue.component("wpe-button-group", WpeButtonGroup);
Vue.component("wpe-button-set", WpeButtonSet);
Vue.component("wpe-radio", WpeRadio);
Vue.component("wpe-link-color", WpeLinkColor);
Vue.component("wpe-info", WpeInfo);
Vue.component("wpe-divider", WpeDivider);
Vue.component("wpe-image-select", WpeImageSelect);
Vue.component("wpe-editor", WpeEditor);
Vue.component("wpe-media", WpeMedia);
Vue.component("wpe-background", WpeBackground);
Vue.component("wpe-section", WpeSection);
Vue.component("wpe-heading", WpeHeading);
Vue.component("wpe-help", WpeHelp);
Vue.component("wpe-options-page", WpeOptionsPage);
